In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Advertising.csv")

In [3]:
df.head()

,TV,radio,newspaper,sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,9.3
3,151.5,41.3,58.5,18.5
4,180.8,10.8,58.4,12.9


In [4]:
X = df.drop(columns="sales")

In [ ]:
y = df["sales"]

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [7]:
polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [8]:
poly_features = polynomial_converter.fit_transform(X)

In [10]:
poly_features.shape

(200, 19)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    poly_features, y, test_size=0.3, random_state=101)

In [13]:
X_train.shape

(140, 19)

In [14]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler = StandardScaler()

In [17]:
scaler.fit(X_train)

StandardScaler()

In [18]:
X_train = scaler.transform(X_train)

In [19]:
X_test = scaler.transform(X_test)

In [20]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [21]:
from sklearn.linear_model import Ridge

In [24]:
ridge_model = Ridge(alpha=10)

In [25]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [26]:
test_predictions = ridge_model.predict(X_test)

In [27]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [29]:
MAE = mean_absolute_error(y_test, test_predictions)

In [30]:
MAE

0.5774404204714163

In [31]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [32]:
RMSE

np.float64(0.894638646131965)

In [33]:
from sklearn.linear_model import RidgeCV

In [42]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring="neg_mean_absolute_error")

In [43]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [44]:
ridge_cv_model.alpha_

np.float64(0.1)

In [45]:
test_predictions = ridge_cv_model.predict(X_test)

In [46]:
MAE = mean_absolute_error(y_test, test_predictions)

In [47]:
MAE

0.427377488434534

In [48]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [49]:
RMSE

np.float64(0.6180719926938822)

In [50]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

LASSO

In [52]:
from sklearn.linear_model import LassoCV

In [81]:
lasso_cv_model = LassoCV(eps=0.001, n_alphas=100, cv=5, max_iter=1000000)

In [82]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, max_iter=1000000)

In [83]:
lasso_cv_model.alpha_

np.float64(0.004943070909225831)

In [84]:
test_predictions = lasso_cv_model.predict(X_test)

In [85]:
MAE = mean_absolute_error(y_test, test_predictions)

In [86]:
MAE

0.4335034618590074

In [87]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [88]:
RMSE

np.float64(0.6063140748984036)

In [89]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [90]:
from sklearn.linear_model import ElasticNetCV

In [92]:
elastic_model = ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1], eps=0.001, n_alphas=100,
                             max_iter=1000000)

In [93]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [94]:
elastic_model.l1_ratio_

np.float64(1.0)

In [95]:
elastic_model.alpha_

np.float64(0.004943070909225831)

In [96]:
test_predictions = elastic_model.predict(X_test)

In [97]:
test_predictions

array([14.16203485, 19.2942685 , 12.34178429, 16.97745571,  8.02340978,
        6.95799942, 20.11875833, 17.32880647, 10.43139937, 19.96174466,
        9.56959473, 13.94205676, 11.90851817, 23.35138146, 19.56656277,
        9.27838151, 12.30485359,  9.30152997,  8.56733436, 21.51633564,
        7.06650884, 19.3377222 , 27.28027149, 24.52239173,  9.17172464,
       11.60918126, 20.73841405,  9.29953525, 12.56948515,  8.40051066,
        8.56984613, 20.03587647, 10.83439653,  6.79505173, 18.18820331,
        9.48107219, 10.41803957,  9.70785725,  7.22932328, 10.85467692,
       12.85491418, 10.51648453, 11.26905127,  7.41516944, 11.54705407,
       10.42233031,  6.02782344, 15.36338733, 13.18723611, 22.67619584,
       10.4721906 , 13.01165791, 14.56684361, 11.90062303, 11.47303307,
        5.59404766, 25.06115365,  9.69468957, 17.44771723, 15.60375637])

In [98]:
MAE = mean_absolute_error(y_test, test_predictions)

In [99]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [100]:
MAE

0.4335034618590074

In [101]:
RMSE

np.float64(0.6063140748984036)